// let name= prompt("Як тебе звати?")
// let age= prompt("Скілки тобі років?")
// console.log(`привіт, ${name}`)
// console.log(`Вітаю в Узбекістані`)
// console.log(`Твій рік народження ${2024 - age} `)

//  let number = +prompt("Введи якесь число", 5)
//  console.log(`обране число: ${number}`)
//  console.log(`Наступне число: ${number + 1}`)
//  console.log(`Наступне число: ${number + 2}`)

let l = +prompt ("Введіть довжину ребра куба")
console.log(`Введене ребро: ${l} см`)
console.log(`Об'єм куба: ${l ** 3}`)
console.log(`Площа стрін куба: ${ 6 * (l ** 2)}`)
